spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      mvc:
        routes:
          - id: account-service
            uri: http://localhost:8081/accounts
            predicates:
              - Path=/accounts/**
          - id: auth-service
            uri: http://localhost:8082/auth
            predicates:
              - Path=/auth/**

server:
  port: 8888