spring:
  application:
    name: account-service-v1
server:
  port: 8081

  datasource:
    url: jdbc:postgresql://localhost:5432/accountdb
    username: postgres
    password: admin123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    root: INFO
    com.vgr: DEBUG   # your base package
    org.springframework.web: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"